example:
  #baseUrl: http://localhost:8080 #API endpoint
  oauth2:
    okta:
      clientId: 0oarolv9yRaQgdIM24x6
      clientSecret: nwKrONKuZJ0mF-dt1EMJOOUzNuXdSOo9IoiLjxdO
      grantType: client_credentials #Instead password grant type
      accessTokenUri: https://dev-734652.okta.com/oauth2/default/v1/token
      scope: custom_service #Created in okta
    keycloak:
      clientId: app-resource-server
      clientSecret: 811b112c-a178-40f5-b512-6caed12fde9c
      grantType: password
      username: manager
      password: manager
      accessTokenUri: http://192.168.1.110:9001/auth/realms/myrealm/protocol/openid-connect/token
      scope: openid profile email
